# Generated by Django 4.2.7 on 2023-11-25 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('growplace', '0002_alter_profile_id_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.CharField(blank=True, max_length=750, null=True),
        ),
        migrations.DeleteModel(
            name='EventDescription',
        ),
    ]
