# Generated by Django 4.2.7 on 2023-11-25 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('growplace', '0004_userevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='userevent',
            name='passed',
            field=models.BooleanField(default=False),
        ),
    ]
